id: env-pi-1
logging:
  format: "%(asctime)s - %(levelname)s - %(name)s [%(lineno)s] - %(message)s"
  path: /home/pi/logs
  level: info
data:
  path: /home/pi/data # where to queue the data to be sent to the server
  input:
    - healthcheck
    - gps
    - bme280
    - sds011
server:
  url: http://192.168.1.1/api # url to post the data to (datalake service)
  token: token
