id: env-pi-1
logging:
  format: "%(asctime)s - %(levelname)s - %(name)s [%(lineno)s] - %(message)s"
  path: /home/pi/logs
  level: info
data:
  output: /home/pi/data
  input:
    sensors:
      - healthcheck
      - gps
      - bme280
      - sds011
server:
  url: http://192.168.1.1/api # url to post the data to (datalake service)
  user: user
  password: password
